#!/usr/bin/env bash

set -e

case "$(uname -s)" in 
    Linux*) CONFIG="install-linux.conf.yaml";;
    Darwin*) CONFIG="install-osx.conf.yaml";;
    *) CONFIG=""
esac

DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"


CONFIG=$(echo "install-$(uname -s).conf.yaml" | awk '{print tolower($0)}')
echo $CONFIG
if [ ! -f ${CONFIG} ]; then
    echo "Unsupported operating system ($(uname -s)), no config file: ${CONFIG}"
    echo "Exiting"
    exit 1
fi


cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" --plugin-dir=dotbot-golang --plugin-dir=dotbot-brew --plugin-dir=dotbot-git --plugin-dir=dotbot-asdf "${@}"
