set number
set relativenumber
set bg=dark
set tabstop=4
set expandtab
set showcmd             " show command in bottom bar
set showmatch           " highlight matching [{()}]
set cursorline
set wildmenu
set lazyredraw          " redraw only when we need to.
set incsearch           " search as characters are entered
set hlsearch            " highlight matches
" turn off search highlight
nnoremap <leader><space> :nohlsearch<CR>

" do not store swp and backup files in same dir
set directory=~/.vim-swp
set backupdir=~/.vim-backup

syntax on
colorscheme tomorrownight
set nocompatible "be iMproved
filetype off
set backspace=2

" move vertically by visual line
nnoremap j gj
nnoremap k gk

" set the runtime path to include Vundle and initialization
"set rtp+=~/.vim/bundle/Vundle.vim
call plug#begin()
Plug 'fatih/vim-go'
call plug#end()
filetype plugin indent on

" Settings for golang
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_fields = 1
let g:go_highlight_types = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_fmt_command = "goimports"

set completeopt+=preview
let g:acp_enableAtStartup = 0
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_smart_case = 1
