set number
set bg=dark
set tabstop=4
set expandtab
set showcmd             " show command in bottom bar
set showmatch           " highlight matching [{()}]
set cursorline
set wildmenu
set lazyredraw          " redraw only when we need to.
set incsearch           " search as characters are entered
set hlsearch            " highlight matches
" turn off search highlight
nnoremap <leader><space> :nohlsearch<CR>
syntax on
colorscheme tomorrownight
set nocompatible "be iMproved
filetype off
set backspace=2

" move vertically by visual line
nnoremap j gj
nnoremap k gk

