#!/usr/bin/env bash

ecr_login() {
    aws_account_id=${AWS_ACCOUNT_ID?:"AWS_ACCOUNT_ID must be set"}
    aws_region=${AWS_REGION:-'us-east-1'}

    aws ecr get-login-password --region ${aws_region} | docker login --username AWS --password-stdin ${aws_account_id}.dkr.ecr.${aws_region}.amazonaws.com
}

ecr_login "$@"
