#!/usr/bin/env zsh

gfmt() {
	echo "Running gofmt"
	gofmt -l -s -w $(find . -type f -name '*.go' -not -path "./vendor/*")
	echo "Running goimports"
	goimports -l -w $(find . -type f -name '*.go' -not -path "./vendor/*")
}

gfmt "$@"