#!/usr/bin/env zsh

venv() {
    local venvs_root
    venvs_root=~/venvs
    if [[ -z $1 ]]; then
        echo "Usage: venv <NAME>"
        return 1
    fi
    if [[ $1 == "off" ]]; then
        echo "param if off"
        deactivate
        return 0
    fi

    if [[ -d $venvs_root/$1 ]]; then

        if [[ -f $venvs_root/$1/bin/activate ]]; then
            VIRTUAL_ENV_DISABLE_PROMPT=1 source $venvs_root/$1/bin/activate
        else
            echo "Folder ~/venvs/$1 exists, but does not seem to be valid virtual environment"
            return 2
        fi
    else
        echo "Venv $1 does not exist. For now - create it manually."
    fi
}

venv "$@"
