bindkey -e

# set up homebrew environment
# this path is only for Apple Silicon, so check if it exists
[[ -f /opt/homebrew/bin/brew ]] && eval "$(/opt/homebrew/bin/brew shellenv)"

# initialize asdf
source $HOME/.asdf/asdf.sh

# add own functions dir to fpath
fpath=( "$HOME/.zsh/functions" "$ASDF_DIR/completions" $fpath )

# enable tab completion
autoload -Uz compinit && compinit

# load own functions
autoload -Uz extract using_port gfmt gcover venv

# load all aliases
source ~/.aliases

# load setup for prompt
source ~/.zsh/prompt.zsh

if [[ $(whoami) = root ]]; then
    umask 0022
else
    umask 0002
fi


# bind fn+left-arrow to go to benening of the line
bindkey "^[[H" beginning-of-line
# bind fn+right-arrow to go to end of the line
bindkey "^[[F" end-of-line
# bind fn+backspace to delete char to the right
bindkey "^[[3~" delete-char
bindkey "^[3;5~" delete-char


zstyle ':completion::complete:*' use-cache on
zstyle ':completion::complete:*' cache-path .zcache
zstyle ':completion:*:cd:*' ignore-parents parent pwd

zstyle ':completion::complete:cd::' tag-order local-directories
zstyle ':completion:*' menu select=2
zstyle ':completion:*' squeeze-slashes true
zstyle ':completion:*:*:kill:*' menu yes select
zstyle ':completion:*:kill:*'   force-list always

# configure command history
setopt appendhistory
export HISTFILE=$HOME/.zhistory
export SAVEHIST=1000
export HISTSIZE=10000

setopt COMPLETE_IN_WORD

setopt NO_BEEP

export GPG_TTY="$(tty)"
#export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
export PATH="/usr/local/opt/postgresql@9.5/bin:$PATH"

if [ -f ~/.private.zshrc ]; then
    source ~/.private.zshrc
fi

# dissable for now, not using it often and it takes some time from starting new instance of a shell
eval "$(direnv hook zsh)"

